---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: blog
  name: blog
spec:
  ports:
    - port: 80
      targetPort: 2368
  selector:
    name: blog
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.20.20.10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      name: blog
  template:
    metadata:
      labels:
        name: blog
    spec:
      containers:
      - name: blog
        image: ghost:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-content
spec:
  storageClassName: tanzu-disk-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
