#!/bin/bash
echo Enter "S" to login to the Supervisor cluster or "W" to login to a workload cluster:
read CLUSTERCHOICE
if [ $CLUSTERCHOICE == "S" ]
then
  echo Please enter the supervisor namespace to which you are trying to login:
  read SUPNS
  echo Please enter your username:
  read USER1
  kubectl vsphere login --vsphere-username $USER1 --server=https://60.60.60.10 --tanzu-kubernetes-cluster-namespace $SUPNS --insecure-skip-tls-verify
elif [ $CLUSTERCHOICE == "W" ]
then
  echo Please enter the name of the workload cluster to which you are trying to login:
  read WKLD
  echo Please enter the name of the supervisor namespace in which the workload cluster resides:
  read SUPNS1
  echo Please enter your username:
  read USER2
  kubectl vsphere login --vsphere-username $USER2 --server=https://60.60.60.10 --tanzu-kubernetes-cluster-namespace $SUPNS1 --tanzu-kubernetes-cluster-name $WKLD --insec>
else
  echo "Invalid Option.  Please try logging in again."
fi
